---
- name: Creating folder for backups
  become: True
  file: >
        path={{server_backup_storage}}
        state=directory
        owner={{ansible_user}}
        group={{ansible_user}}
        recurse=True

- name: Make MySQL backup
  include: mysql.yml
  when: "'mysql' in dbs"

...