---
- include: get_facts.yml
#- include: key_install.yml

- hosts: db_master
  vars:
      dbs:
        - 'mysql'
  roles:
    - check_dbconnection

#- hosts: db_slave
#  roles:
#    - makedb_backup
#
#- hosts: db_backup_master
#  roles:
#    - replication
...