---
- include: get facts.yml

- hosts: db_backup_master
  roles:
    - check_dbconnection

- hosts: db_backup_master
  roles:
    - makedb_backup

- hosts: db_backup_master
  roles:
    - replication
...