Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-7.3"
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
    end
    config.vm.define "dev_php_app_01" do |dev_php_app_01|
       dev_php_app_01.vm.network "private_network", ip: "192.168.34.15"
       dev_php_app_01.vm.provision "ansible" do |ansible|
           ansible.playbook = "app_setup.yml"
           ansible.inventory_path= "develop"
           ansible.limit = 'all'
       end
    end

    config.vm.define "dev_mysql_01", primary: true do |dev_mysql_01|
        config.vm.box = "bento/centos-7.1"
        dev_mysql_01.vm.network "private_network", ip: "192.168.11.210", bridge: "eth0"
        config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
            vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
    end
    config.vm.define "backup_work_01", primary: true do |backup_work_01|
        config.vm.box = "bento/centos-7.1"
        backup_work_01.vm.network "private_network", ip: "192.168.11.10", bridge: "eth0"
        config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
            vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
    end
    config.vm.define "master_db_01", primary: true do |master_db_01|
        config.vm.box = "bento/centos-7.3"
        master_db_01.vm.network "private_network", ip: "192.168.12.12"
        config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
#            vb.customize ["modifyvm", :id, "--memory", "2048"]
            vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
    end
    config.vm.define "master_db_02", primary: true do |master_db_01|
            config.vm.box = "bento/centos-7.3"
            master_db_01.vm.network "private_network", ip: "192.168.12.13"
            config.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"]
    #            vb.customize ["modifyvm", :id, "--memory", "2048"]
                vb.customize ["modifyvm", :id, "--cpus", "1"]
            end
        end
    config.vm.define "slave_db_01", primary: true do |slave_db_01|
        config.vm.box = "bento/centos-7.3"
        slave_db_01.vm.network "private_network", ip: "192.168.12.15"
        config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
#            vb.customize ["modifyvm", :id, "--memory", "2048"]
            vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
    end
    config.vm.define "ci_mashine", primary: true do |ci_mashine|
        config.vm.box = "bento/centos-7.1"
        ci_mashine.vm.network "private_network", ip: "192.168.12.12", bridge: "eth0"
        config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
            vb.customize ["modifyvm", :id, "--cpus", "1"]
        end
    end
    config.ssh.insert_key = false
    config.ssh.forward_agent = true
end
